Remove unused compare_version
docker.version()['ApiVersion'] in the function
gets error in docker 1.10.6

>>> import docker
>>> docker.version
'1.10.6'
>>>
>>> docker.version()['ApiVersion']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'str' object is not callable

The patch removes compare_version due to
the two functions are unused.

Change-Id: If867394725eca7ee2dd7ed46c21ba4468d756f4a