Can not get a valid error message when executing zun attach error
When 'zun attach' failed due to the low version of 'websocket-client'

the log error message is
TypeError: unsupported operand type(s) for %: 'error' and 'dict'

Modified to make the error information readable.

Change-Id: Ibcfa6f00d81af3c93828198b2914f1d46edbc7a2
Closes-Bug: #1742113