Fix another upgrade from docker-py to docker place
This patch fix the error from nova, when using nova-docker driver:
CRITICAL nova Unhandled error: AttributeError: 'module' object has no attribute 'Client'

Change-Id: Ie9b2655b2353a40e504ac2e4bd3c59f829d42a39
Partial-Implements: blueprint adopt-docker-py-2.0-api